### ISSUE TITLE
Use of 'chunks' option in processlist

### ISSUE THREAD

**Issue by amanmdesai** [HEP-FCC/FCCAnalyses#296]
Hello,

This is to report the following problem regarding the usage of 'chunks' parameter in the processList. As I understand the aim of this parameter is to allow splitting of a large output root file into smaller files. 

As an example, when I run the file: 
https://github.com/HEP-FCC/FCCAnalyses/blob/master/examples/FCCee/higgs/mH-recoil/mumu/analysis_stage1.py

with the modification in the process list: 

```python
p8_ee_ZZ_ecm240':{'fraction':0.1,'chunks':20}
```
command used to run (within the FCCAnalyses/examples/FCCee/higgs/mH-recoil/mumu folder): 

```code
fccanalysis run analysis_stage1.py
```

I face the following error:

```code
----> Warning: Provided output path is absolute, "outputDir" from analysis script will be ignored!
----> Info: Output file path:
            /p8_ee_ZZ_ecm240/chunk0.root
----> Error: During the execution of the analysis file exception occurred
```

I am using the master branch of FCCAnalyses software.  
 
Could you please help me with this?

Thanks
Aman

**Comment by kjvbrt** [comment]
Hello @amanmdesai,

Thanks for reporting the issue :)

the problem is more related to the handling of the path for the output file. There was recently this
PR https://github.com/HEP-FCC/FCCAnalyses/pull/292, which changed it a bit.

With this PR https://github.com/HEP-FCC/FCCAnalyses/pull/297, you should get output file path like this:
```
----> Info: Output file path:
            outputs/FCCee/higgs/mH-recoil/mumu/stage1/p8_ee_ZZ_ecm240/chunk1.root
```

I'm not sure if I also did not break something when running in batch mode :(

**Comment by amanmdesai** [comment]
I am able to run the scripts. Thanks.
